CONFIG_NAME: "bird"
dataset_name: "birds"
data_dir: "../data/birds"

imsize: 256
z_dim: 100
cond_dim: 512
manual_seed: 100
cuda: True

clip4evl: { "src": "clip", "type": "ViT-B/32" }
clip4trn: { "src": "clip", "type": "ViT-B/32" }
clip4text: { "src": "clip", "type": "ViT-B/32" }

stamp: "normal"
state_epoch: 1
max_epoch: 1502
batch_size: 32
gpu_id: 0
nf: 64
ch_size: 3

lr_g: 0.0001
lr_d: 0.0004
sim_w: 4.0

test_interval: 10 #5
save_interval: 5

sample_times: 12
npz_path: "../data/birds/npz/bird_val256_FIDK0.npz"
